version: 2
jobs:
    build:
        docker:
            - image: python:3.6

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    - v1-dependencies-

            - run:
                name: Install dependencies
                command: |
                    touch /etc/apt/sources.list.d/debian-mozilla.list
                    deb http://mozilla.debian.net/ jessie-backports firefox-release
                    wget mozilla.debian.net/pkg-mozilla-archive-keyring_1.1_all.deb
                    dpkg -i pkg-mozilla-archive-keyring_1.1_all.deb
                    rm pkg-mozilla-archive-keyring_1.1_all.deb
                    apt-get update
                    apt-get install -y firefox
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt

            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}

            - run:
                name: Run
                command: |
                    cp credentials.py.example credentials.py
                    ./run.sh
