version: 2
jobs:
    build:
        docker:
            - image: python:3.6

        working_directory: ~/repo

        steps:
            - setup_remote_docker:
                reusable: true
                exclusive: true

            - run:
                name: Install dependencies
                command: docker build -t dwbot .

            - run:
                name: Run
                command: docker run -e login=$login -e password=$password dwbot
